### ISSUE TITLE
OnActionExecutionAsync not overridable

### ISSUE THREAD

**Issue by steveschmitt** [Breeze/breeze.server.net#195]
Problem introduced in PR #191

**Comment by biegehydra** [comment]
I think `BreezeQueryFilterAttribute : Attribute, IAsyncActionFilter` can be changed back to `BreezeQueryFilterAttribute : ActionFilterAttribute` and still work - while keep the changes made in #191. I didn't realize but `ActionFilterAttribute : IAsyncActionFilter` and is overridable. 

[Dotnet Source Viewer](https://source.dot.net/#Microsoft.AspNetCore.Mvc.Core/Filters/ActionFilterAttribute.cs,f91a81f44ccf188b,references)

**Comment by graphicsxp** [comment]
hello, 
any news on this ?  can it be fixed soon ?

**Comment by graphicsxp** [comment]
ok, let me know here when it's done, we really need this :)
thanks a lot !

**Comment by steveschmitt** [comment]
Fixed now, in [Breeze.AspNetCore.NetCore](https://www.nuget.org/packages/Breeze.AspNetCore.NetCore) version 7.2.2.

**Comment by graphicsxp** [comment]
We want to keep using OnActionExecuted but although breeze let us override it, it does not implement it anymore, am i correct ?
Could you shine some light here please ?

**Comment by steveschmitt** [comment]
Looks like another oversight by me and @biegehydra .  

In the base [ActionFilterAttribute](https://source.dot.net/#Microsoft.AspNetCore.Mvc.Core/Filters/ActionFilterAttribute.cs,f91a81f44ccf188b,references) class, `OnActionExecutionAsync` calls both `OnActionExecuting` and `OnActionExecuted`.  The Breeze [QueryFilter](https://github.com/Breeze/breeze.server.net/blob/master/DotNet/Breeze.AspNetCore.NetCore/QueryFilter.cs) does not call those methods, but it should.

Can you help me determine where & when QueryFilter should call those methods?

**Comment by biegehydra** [comment]
Yeah @steveschmitt seems we just can't get a break. I reckon `OnActionExecuting(executingContext);` can be called right at the beginning of `OnActionExecutionAsync`. 

For `OnActionExecuted`, it's a little more confusing. Something like this after `var executedContext = await next();`:
```
OnActionExecuted(new ActionExecutedContext(executedContext, new List<IFilterMetadata>(), executedContext.Controller) {
            Canceled = executedContext.Canceled,
            Exception = executedContext.Exception,
            ExceptionDispatchInfo = executedContext.ExceptionDispatchInfo,
            Result = executedContext.Result
        });
```
I think something like this is correct, but it might supposed be `executingContext` in the `ActionExecutedContext` constructor

**Comment by biegehydra** [comment]
This stackoverflow post seems to confirm my guess. https://stackoverflow.com/a/59062033/15947449

**Comment by steveschmitt** [comment]
I'm thinking that we would have the OnActionExecuted at the end, after we had run the query, like this:
```cs
    override public async Task OnActionExecutionAsync(ActionExecutingContext executingContext, ActionExecutionDelegate next) {
      var cancellationToken = executingContext.HttpContext.RequestAborted;

      OnActionExecuting(executingContext);
      if (!executingContext.ModelState.IsValid) {
        executingContext.Result = new BadRequestObjectResult(executingContext.ModelState);
      }
      if (executingContext.Result != null) {
        return;
      }

      var executedContext = await next();

      // ... apply and execute query ... set executedContext.Result ...

      OnActionExecuted(executedContext);
    }
```
@graphicsxp Do you think that would work for you?

**Comment by steveschmitt** [comment]
I'm having second thoughts about using `ToListAsync()` because of [this issue](https://github.com/dotnet/efcore/issues/18221) and [this SO post](https://stackoverflow.com/questions/28543293/entity-framework-async-operation-takes-ten-times-as-long-to-complete).  Basically, queries take 10x as long to complete with `ToListAsync()` whenever there are `varbinary(max)` or `nvarchar(max)` columns.

Is it worth paying that penalty for the ability to pass a CancellationToken?

**Comment by graphicsxp** [comment]
personnaly I don't have the need to pass a cancellation token, so if you rollback to onactionexecuted I'll be happy.

**Comment by biegehydra** [comment]
I don't know about others but a lot of our usage with Breeze is for client side pagination. 

Cancellation tokens are particular useful when paginating a table that has longer queries. If a user changes their query or goes to the next page while a previous query is still running, we just cancel that request and start a new one.

This isn't possible without ToListAsync(). My experience before adding that was it would have to complete all queries leading up to the last one before displaying results, which is unacceptable for us.

What do you think about a BreezeAsyncQueryFilter or something along those lines as a separate filter? Best of both worlds, the class isn't very long

**Comment by graphicsxp** [comment]
this sounds like a good solution to me, giving the choice between async and non-async filters.

**Comment by steveschmitt** [comment]
As of release [7.3.0](https://breeze.github.io/doc-net/release-notes.html#730-may-15-2024), there are now separate [BreezeQueryFilter] and [BreezeAsyncQueryFilter] attributes.  Use the one that you prefer.

**Comment by steveschmitt** [comment]
Closing this because I think the concerns have been addressed
